name: tw scraper

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '58 19 * * *'

env:
  RELEASE_TAG: 'tw'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      - name: Get Streamlink latest version
        id: getver
        run: |
          ver=$(pip index versions streamlink 2>/dev/null | head -n 1 | awk '{print $2}')
          echo "version=$ver" >> $GITHUB_OUTPUT
        # ver=$(python -c "import json,urllib.request; print(json.load(urllib.request.urlopen('https://pypi.org/pypi/streamlink/json'))['info']['version'])")

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-streamlink-${{ steps.getver.outputs.version }}

      - name: Set up venv and install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install streamlink

      - name: Run scraper
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          .venv/bin/python tw.py

      - name: Check whether tag exists # only needed for the first run
        id: tag_check
        run: |
          # fetch remote refs and check for the tag; set output for later conditional
          if git ls-remote --tags origin refs/tags/$RELEASE_TAG | grep -q "refs/tags/$RELEASE_TAG"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Delete release and tag
        if: steps.tag_check.outputs.exists == 'true'
        run: gh release delete "$RELEASE_TAG" --cleanup-tag --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Wait for deletion to propagate
        if: steps.tag_check.outputs.exists == 'true'
        run: sleep 10
        shell: bash

      - name: Verify tag and release deletion
        if: steps.tag_check.outputs.exists == 'true'
        run: |
          if git ls-remote --tags origin refs/tags/$RELEASE_TAG | grep -q "refs/tags/$RELEASE_TAG"; then
            echo "Tag still exists!"; exit 1;
          fi
          gh release view "$RELEASE_TAG" && { echo "Release still exists!"; exit 1; } || echo "Release deleted."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.m3u8"
          allowUpdates: false
          generateReleaseNotes: false
          replacesArtifacts: true
          removeArtifacts: true
          prerelease: false
          draft: false
          makeLatest: false
          tag: ${{ env.RELEASE_TAG }}